services:
  backend:
    build:
      context: ../backend
    ports:
      - 8090:8080
    environment:
      - PORT=8080
      - DBURL=mysql
      - DBUSER=root
      - DBPASSWORD=password
      - DBDATABASE=todo
      - DBPORT=3306
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
      args:
        - APIURL=http://localhost:8090
    ports:
      - 8100:80
    depends_on:
      - node_frontend
      - mysql

  node_frontend:
    image: node:16-alpine
    working_dir: /usr/src/app
    volumes:
      - ../frontend:/usr/src/app
    command: ["npm", "install"]
    environment:
      APIURL: "http://localhost:8090"

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ../backend/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 3
